services:
  main-service:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      postgres-service:
        condition: service_healthy
      redis-service:
        condition: service_healthy
    volumes:
      - ./codebase:/leaderboardx-root/codebase
      - ./alembic:/leaderboardx-root/alembic
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:pass@postgres-service:5432/leaderboardx-db
      - REDIS_URL=redis://redis-service:6379
      - DEBUG=true
      - SECRET_KEY=WgEPVP24jDgvDQYK
      - APP_NAME=LeaderboardX Development
      - APP_VERSION=0.0.1
      - STUDIO_DASHBOARD_PATH=/__studio
      - ADMIN_DASHBOARD_PATH=/__admin

  postgres-service:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=leaderboardx-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - postgres_data_lbx_v2:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d leaderboardx-db"]
      interval: 2s
      timeout: 3s
      retries: 30

  redis-service:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 2s
      retries: 30

volumes:
  postgres_data_lbx_v2:
