services:
  main-service:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres-service
      - redis-service
    volumes:
      - ./codebase:/leaderboardx-root/codebase
      - ./alembic:/leaderboardx-root/alembic
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:pass@postgres:5432/leaderboard
      - REDIS_URL=redis://redis:6379
      - DEBUG=true
      - SECRET_KEY=WgEPVP24jDgvDQYK
      - APP_NAME=LeaderboardX Development

  postgres-service:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=leaderboard
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis-service:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: