services:
  main-service:
    build: .
    env_file:
      - .env.staging
    ports:
      - "7010:8000"
    depends_on:
      - postgres-service
      - redis-service
    environment:
      - DEBUG=true
    volumes:
      - ./codebase:/leaderboardx-root/codebase
      - ./alembic:/leaderboardx-root/alembic
    mem_limit: 512m
    cpus: 0.75
    restart: unless-stopped

  postgres-service:
    image: postgres:15-alpine
    env_file:
      - .env.staging
    volumes:
      - postgres_data_stage:/var/lib/postgresql/data
    ports:
      - "7015:5432"
    mem_limit: 1024m
    cpus: 1.0
    restart: unless-stopped

  redis-service:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "7016:6379"
    mem_limit: 256m
    cpus: 0.5

volumes:
  postgres_data_stage:
