"""Initial schema with UUID xid fields

Revision ID: 63b92eb0771f
Revises: 
Create Date: 2025-12-31 11:37:48.977190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63b92eb0771f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaderboards_id'), 'leaderboards', ['id'], unique=False)
    op.create_index(op.f('ix_leaderboards_name'), 'leaderboards', ['name'], unique=False)
    op.create_table('users',
    sa.Column('xid', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("device_id ~ '^[A-Za-z0-9\\-]+$'", name='check_device_id_format'),
    sa.PrimaryKeyConstraint('xid')
    )
    op.create_index('ix_users_device_id', 'users', ['device_id'], unique=False)
    op.create_index('ix_users_xid', 'users', ['xid'], unique=False)
    op.create_table('scores',
    sa.Column('xid', sa.UUID(), nullable=False),
    sa.Column('user_xid', sa.UUID(), nullable=False),
    sa.Column('leaderboard_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['leaderboard_id'], ['leaderboards.id'], ),
    sa.ForeignKeyConstraint(['user_xid'], ['users.xid'], ),
    sa.PrimaryKeyConstraint('xid')
    )
    op.create_index('ix_scores_leaderboard_value', 'scores', ['leaderboard_id', 'value'], unique=False)
    op.create_index('ix_scores_user_leaderboard', 'scores', ['user_xid', 'leaderboard_id'], unique=False)
    op.create_index('ix_scores_xid', 'scores', ['xid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scores_xid', table_name='scores')
    op.drop_index('ix_scores_user_leaderboard', table_name='scores')
    op.drop_index('ix_scores_leaderboard_value', table_name='scores')
    op.drop_table('scores')
    op.drop_index('ix_users_xid', table_name='users')
    op.drop_index('ix_users_device_id', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_leaderboards_name'), table_name='leaderboards')
    op.drop_index(op.f('ix_leaderboards_id'), table_name='leaderboards')
    op.drop_table('leaderboards')
    # ### end Alembic commands ###
