services:
  frontend-service:
    build: .
    ports:
      - "9020:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    mem_limit: 256m
    cpus: 0.5
    restart: unless-stopped
